
const translations = {
  "pt": {
    "title": "Currículo | Iago de Souza Gomes",
    "name": "Iago de Souza Gomes",
    "role": "Estudante de Ciência da Computação",
    "intro": "Currículo interativo",
    "nav_about": "Sobre",
    "nav_education": "Formação",
    "nav_experience": "Experiência",
    "nav_training": "Capacitação",
    "nav_projects": "Projetos de Extensão",
    "nav_contact": "Contato",
    "nav_pdf": "Currículo PDF",
    "about_title": "Sobre",
    "about_text": "Sou um estudante de Ciência da Computação no IESB, apaixonado por programação e pelo universo da tecnologia. Tenho 21 anos e estou em uma jornada contínua de aprendizado, sempre buscando novos desafios e conhecimentos para me aprimorar como desenvolvedor.",
    "education_title": "Formação",
    "education_course": "Graduação em Ciência da Computação – em curso",
    "education_details": "Início em março de 2023. Cursando atualmente o 7º semestre no IESB, Campus Sul, em Brasília, DF. Conclusão prevista para final de 2026",
    "education_subjects_title": "Matérias Relevantes",
    "education_subjects_list": "Algoritmos e Programação de Computadores I, Laboratório Práticas, Banco de Dados I, Sistemas Digitais, Algoritmose Programação de Computadores II, Laboratório Práticas II, Teoria da computação, Arquitetura  e  Organização  de Computadores, Estrutura de Dados, Banco de Dados II, Engenharia de Software, Inteligência Artificial, Programação Orientada a Objetos, Governância de TI e Mapeamento de Processos, Probabilidade e Estatística, Tecnologias Web, Computação Gráfica, Programação para Dispositivos Móveis e Paradigmas de Linguagem de Programação.",
    "experience_title": "Experiência",
    "experience_1_title": "Bolsista de Projeto – PGFN / UNB",
    "experience_1_date": "02/2025 – 02/2026",
    "experience_1_desc": [
      "Atuação em projeto remoto da Procuradoria-Geral da Fazenda Nacional (PGFN) em parceria com a Universidade de Brasília.",
      "Desenvolvimento e manutenção de scripts em <strong>Python</strong> voltados para web scraping de dados institucionais.",
      "Monitoramento diário da execução dos códigos, com identificação, análise e correção de falhas operacionais.",
      "Implementação de otimizações de desempenho nos processos de scraping, visando maior eficiência e estabilidade.",
      "Colaboração no desenvolvimento de protótipos de soluções de segurança da informação, com foco na proteção de dados sensíveis do órgão.",
      "Elaboração de relatórios técnicos e comunicação de incidentes e melhorias ao time do projeto."
    ],
    "experience_2_title": "Bolsista de Projeto – PET Saúde / UNB",
    "experience_2_date": "10/2025 – em andamento",
    "experience_2_desc": [
        "Atuação em projeto do PET-Saúde, com foco em soluções digitais para apoio à comunicação e acessibilidade em serviços de saúde.",
        "Participação em atividades de infraestrutura e manutenção de sites, garantindo disponibilidade, organização e usabilidade.",
        "Desenvolvimento de chatbots para comunicação com usuários, visando melhoria no atendimento e no acesso à informação.",
        "Adaptação e melhoria de interfaces no site GOV.BR, com foco em acessibilidade digital e apoio a pessoas com dificuldades de navegação.",
        "Colaboração em ajustes técnicos voltados à experiência do usuário (UX) e inclusão digital."
    ],
    "training_title": "Capacitação Complementar",
    "training_1_title": "Curso inglês CNA",
    "training_1_desc": ["Data: Março de 2022", "Carga Horária: 500 horas", "Instituição: CNA"],
    "training_2_title": "Curso completo de Lógica de Programação e Algoritmos",
    "training_2_desc": ["Data: 2 de abril de 2022", "Carga horária: 2,5 horas", "Instituição: Udemy"],
    "training_3_title": "Curso C: conhecendo a linguagem das linguagens",
    "training_3_desc": ["Data: 24 de Julho de 2024", "Carga horária: 8 horas", "Instituição: Alura"],
    "training_4_title": "Curso C: avançando na linguagem",
    "training_4_desc": ["Data: 24 de Julho de 2024", "Carga horária: 8 horas", "Instituição: Alura"],
    "training_5_title": "Curso C: recursos avançados da linguagem",
    "training_5_desc": ["Data: 24 de Julho de 2024", "Carga horária: 8 horas", "Instituição: Alura"],
    "training_6_title": "Curso formação linguagem C",
    "training_6_desc": ["Data: 24 de julho de 2024", "Carga horária: 26 horas", "Instituição: Alura"],
    "training_7_title": "Curso MySQL Administrator: configurando e monitorando o servidor",
    "training_7_desc": ["Data: 24 de Julho de 2024", "Carga horária: 10 horas", "Instituição: Alura"],
    "training_8_title": "Curso Java: criando a sua primeira aplicação",
    "training_8_desc": ["Data: 05 de novembro de 2024", "Carga horária: 8 horas", "Instituição: Alura"],
    "training_9_title": "Curso Excel: domine o editor de planilhas",
    "training_9_desc": ["Data: 01 de outubro de 2024", "Carga horária: 8 horas", "Instituição: Alura"],
    "training_10_title": "Curso Python: crie a sua primeira aplicação",
    "training_10_desc": ["Data: 10 de fevereiro de 2025", "Carga horária: 8 horas", "Instituição: Alura"],
    "projects_title": "Projetos de extensão",
    "project_1_desc": "App de mobilidade: calcula rotas otimizadas entre paradas de ônibus",
    "project_1_link": "App PARTIU",
    "project_2_desc": "Site de listagens: plataforma interativa para listagem e gerenciamento de itens.",
    "project_2_link": "Site PIXELPLIST",
    "project_3_desc": "Arquitetura Distribuída com Balanceamento DNS e Sessão Centralizada",
    "project_3_link": "Trabalho de Redes",
    "contact_title": "Contato",
    "contact_phone": "Telefone",
    "contact_github": "Github",
    "contact_linkedin": "LinkedIn",
    "contact_email": "Email",
    "copy_phone_notification": "Número de telefone copiado!",
    "copy_email_notification": "Email copiado!",
    "back_to_top": "Voltar ao Topo",
    "pdf_title": "Currículo em PDF",
    "pdf_file": "pdf/Iago_deSouzaGomes_Currículo.pdf"
  },
  "en": {
    "title": "Resume | Iago de Souza Gomes",
    "name": "Iago de Souza Gomes",
    "role": "Computer Science Student",
    "intro": "Interactive Resume",
    "nav_about": "About",
    "nav_education": "Education",
    "nav_experience": "Experience",
    "nav_training": "Professional Development",
    "nav_projects": "Projects",
    "nav_contact": "Contact",
    "nav_pdf": "PDF Resume",
    "about_title": "About Me",
    "about_text": "I am a Computer Science student at IESB, deeply passionate about software development and technology. At 21, I am on a continuous learning journey, constantly seeking new challenges and expertise to excel as a developer.",
    "education_title": "Education",
    "education_course": "B.S. in Computer Science (Ongoing)",
    "education_details": "Started in March 2023. Currently in the 7th semester at IESB, South Campus (Brasília, DF). Expected graduation: late 2026.",
    "education_subjects_title": "Relevant Coursework",
    "education_subjects_list": "Algorithms and Programming I & II, Data Structures, Database Systems I & II, Digital Systems, Theory of Computation, Computer Architecture, Software Engineering, Artificial Intelligence, Object-Oriented Programming (OOP), IT Governance and Process Mapping, Probability and Statistics, Web Technologies, Computer Graphics, Mobile Development, and Programming Paradigms.",
    "experience_title": "Professional Experience",
    "experience_1_title": "Project Scholar – PGFN / UNB",
    "experience_1_date": "Feb 2025 – Feb 2026",
    "experience_1_desc": [
      "Contributed to a remote project for the Attorney General's Office of the National Treasury (PGFN) in partnership with the University of Brasília (UnB).",
      "Developed and maintained <strong>Python</strong> scripts for automated web scraping of institutional data.",
      "Performed daily monitoring of automated tasks, identifying and resolving operational bottlenecks and failures.",
      "Implemented performance optimizations in scraping workflows, improving system stability and data throughput.",
      "Collaborated on information security prototypes to safeguard sensitive governmental data.",
      "Drafted technical reports and effectively communicated system improvements to the engineering team."
    ],
    "experience_2_title": "Project Scholar – PET Saúde / UNB",
    "experience_2_date": "Oct 2025 – Present",
    "experience_2_desc": [
        "Working on the PET-Saúde project, developing digital solutions to enhance communication and accessibility in public health services.",
        "Managing website infrastructure and maintenance to ensure high availability and user-centric design.",
        "Developing chatbots to streamline user interaction and facilitate access to critical health information.",
        "Optimizing GOV.BR interfaces with a focus on digital accessibility and inclusive navigation for users with disabilities.",
        "Collaborating on technical UX adjustments to foster digital inclusion and accessibility standards."
    ],
    "training_title": "Certifications & Training",
    "training_1_title": "CNA English Course",
    "training_1_desc": ["Date: March 2022", "Duration: 500 hours", "Institution: CNA"],
    "training_2_title": "Logic & Algorithms Masterclass",
    "training_2_desc": ["Date: April 2, 2022", "Duration: 2.5 hours", "Institution: Udemy"],
    "training_3_title": "C Programming: Fundamentals",
    "training_3_desc": ["Date: July 24, 2024", "Duration: 8 hours", "Institution: Alura"],
    "training_4_title": "C Programming: Intermediate Techniques",
    "training_4_desc": ["Date: July 24, 2024", "Duration: 8 hours", "Institution: Alura"],
    "training_5_title": "C Programming: Advanced Resources",
    "training_5_desc": ["Date: July 24, 2024", "Duration: 8 hours", "Institution: Alura"],
    "training_6_title": "C Programming Specialization",
    "training_6_desc": ["Date: July 24, 2024", "Duration: 26 hours", "Institution: Alura"],
    "training_7_title": "MySQL Administration: Server Config & Monitoring",
    "training_7_desc": ["Date: July 24, 2024", "Duration: 10 hours", "Institution: Alura"],
    "training_8_title": "Java: Building Your First Application",
    "training_8_desc": ["Date: Nov 5, 2024", "Duration: 8 hours", "Institution: Alura"],
    "training_9_title": "Excel: Advanced Spreadsheet Management",
    "training_9_desc": ["Date: Oct 1, 2024", "Duration: 8 hours", "Institution: Alura"],
    "training_10_title": "Python: Application Development Essentials",
    "training_10_desc": ["Date: Feb 10, 2025", "Duration: 8 hours", "Institution: Alura"],
    "projects_title": "Portfolio & Extension Projects",
    "project_1_desc": "Mobility App: Optimized route calculation for public transit systems.",
    "project_1_link": "PARTIU App",
    "project_2_desc": "Listing Platform: Interactive system for item management and categorization.",
    "project_2_link": "PIXELPLIST Site",
    "project_3_desc": "Distributed Systems: DNS Balancing and Centralized Session management architecture.",
    "project_3_link": "Network Systems Project",
    "contact_title": "Contact",
    "contact_phone": "Phone",
    "contact_github": "GitHub",
    "contact_linkedin": "LinkedIn",
    "contact_email": "Email",
    "copy_phone_notification": "Phone number copied to clipboard!",
    "copy_email_notification": "Email address copied to clipboard!",
    "back_to_top": "Back to Top",
    "pdf_title": "Resume in PDF",
    "pdf_file": "pdf/Iago_de Souza Gomes_Resume.pdf"
  }
}
